format:
    fourmolu -i exe lib ui
    find exe lib ui -name '*.cabal' -exec cabal-fmt -i {} \;

format-check:
    fourmolu -c -q exe lib ui > /dev/null
    find exe lib ui -name '*.cabal' -exec cabal-fmt -c {} \;

build t:
    cabal build -O0 ${{t}}

build-all:
    cabal build -O0 all
