name: ${NETWORK}
services:


  cardano-node:
    image: cardanofoundation/cardano-deposit-wallet:${WALLET_TAG}
    environment:
      CARDANO_NODE_SOCKET_PATH: /ipc/${NODE_SOCKET_NAME}
    volumes:
      - ${NODE_DB}:/data
      - ${NODE_SOCKET_DIR}:/ipc
    restart: on-failure
    user: ${USER_ID}:${GROUP_ID}
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
    entrypoint: []
    command: >
      ./cardano-node run --topology ./configs/${NETWORK}/topology.json
        --database-path /data
        --socket-path /ipc/${NODE_SOCKET_NAME}
        --config ./configs/${NETWORK}/config.json
        +RTS -N -A16m -qg -qb -RTS

  cardano-deposit-wallet:
    image: cardanofoundation/cardano-deposit-wallet:${WALLET_TAG}
    volumes:
      - ${WALLET_DB}:/wallet-db
      - ${NODE_SOCKET_DIR}:/ipc
    ports:
      - ${WALLET_PORT}:8090
      - ${DEPOSIT_WALLET_UI_PORT}:8092
    entrypoint: []
    command: >
       ./cardano-deposit-wallet serve
        --node-socket /ipc/${NODE_SOCKET_NAME}
        --database /wallet-db
        --listen-address 0.0.0.0
        --ui-deposit-port 8092
        --testnet ./configs/${NETWORK}/byron-genesis.json

    user: ${USER_ID}:${GROUP_ID}
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"

  mithril:
    image: ghcr.io/input-output-hk/mithril-client:${MITHRIL_TAG}
    user: ${USER_ID}:${GROUP_ID}
    volumes:
      - ${NODE_DB}:/app/db
    environment:
      AGGREGATOR_ENDPOINT: ${AGGREGATOR_ENDPOINT}
      GENESIS_VERIFICATION_KEY: ${GENESIS_VERIFICATION_KEY}
    profiles:
      - mithril
